name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git version semantica
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease-${increment}"
      id: version
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "new version: $NEW_VERSION !!!!!!! :)"

    # - name: Construir imagen de docker
    #   run: |
    #     docker build -t epsilon88/docker-graphql:0.0.2 .
    #     docker build -t epsilon88/docker-graphql:latest .

    # - name: Sube la imagen de docker
    #   run: |
    #     docker push epsilon88/docker-graphql:0.0.2
    #     docker push epsilon88/docker-graphql:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
